### ISSUE TITLE
[EOS] Sharing does not work

### ISSUE THREAD

**Issue by jnweiger** [owncloud/product#129] opened 2020-07-22 23:01 UTC
Reproduce on ocis 1.0.0-beta8 with eos installed via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

firefox https://xxx.xxx.xxx.xxx:9200

*  log in as einstein,
* create a few files and folders,
* share them with user marie and or feynman
![image](https://user-images.githubusercontent.com/1108546/88237540-ba7eb380-cc7f-11ea-85c7-8ec7f4d60a47.png)

* log in as user marie (different browser or private browsing tab)
* check files. Nothing arrived. 
* click open 'Shared with me'  Nothing is listed there.
![image](https://user-images.githubusercontent.com/1108546/88237653-f87bd780-cc7f-11ea-8b0c-9f827f32596b.png)

Expected behaviour:
* share receipient sees what share originator shares.

**Comment by PVince81** [comment] 2020-08-24 10:27
@butonic @labkode

**Comment by PVince81** [comment] 2020-08-25 13:24
some attempts here at reconfiguring the storages: https://github.com/owncloud/ocis/pull/484

**Comment by PVince81** [comment] 2020-08-25 15:11
a solution was found, now in the updated config and dosc in https://github.com/owncloud/product/issues/129

however, uploading is broken: this is because the UI is using "remote.php/dav/files" for uploading while the other operations use "remote.php/webdav". The latter maps to the home storage but the former to the global non-home storage.

We'll attempt to fix "remote.php/dav/files" to be simply rewired to the same handler like "remote.php/webdav" if the specified user matches. Otherwise we either fail with a 403 like OC 10, or optionally could redirect to the non-home storage.

@butonic as discussed

**Comment by PVince81** [comment] 2020-08-25 15:13
- [ ] fix dav/files namespace is broken because it should use /home not /oc or /eos
    - in ocdav check if dav/files/<userid> = the current users id,
       - when true -> /home
       - when false -> /eos/{{substr 0 1 .Id.OpaqueId}}/{{.Id.OpaqueId}}
- [ ] to raise: split docker compose files into dedicated eos and owncloud driver setups
- [ ] to raise: clarify env vars for EOS DRIVER vs EOS PROVIDER specific configuration
- [ ] to raise / separate PR: update names.md from https://github.com/owncloud/ocis/pull/484 to the new solution and make it a good documentation page to clarify the namespaces
- [ ] check how the owncloud storage driver needs to be changed to match the eos setup

**Comment by PVince81** [comment] 2020-08-25 15:55
draft PR here for the dav files rewiring: https://github.com/cs3org/reva/pull/1120

**Comment by PVince81** [comment] 2020-08-26 13:26
we have a potential solution, it requires to combine following:
- [ ] updated doc and docker-compose for the correct EOS setup: https://github.com/owncloud/ocis/pull/484
- [ ] reva fix for error handling: https://github.com/cs3org/reva/pull/1124
- [ ] dav files rewiring to the home storage: https://github.com/cs3org/reva/pull/1125

**Comment by PVince81** [comment] 2020-08-27 10:01
all merged in ocis branch and confirmed that sharing is working now with EOS there, closing

**Closed by PVince81** 2020-08-27 10:01 UTC
Labels: C1-oCIS, OCIS-Sprint-16, OCIS-Sprint-17, bug, p2-high

**Comment by jnweiger** [comment] 2020-09-16 15:57
retested with rc1 on eos: shares appear in shared with me and can be accepted. 
Remaining issues regarding sharing include
* https://github.com/owncloud/ocis/issues/582 
* https://github.com/owncloud/ocis/issues/568
* https://github.com/owncloud/ocis/issues/583
